# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqtlinesfit.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(903, 835)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.left_grid = QtWidgets.QWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_grid.sizePolicy().hasHeightForWidth())
        self.left_grid.setSizePolicy(sizePolicy)
        self.left_grid.setObjectName("left_grid")
        self.main_figure = QtWidgets.QVBoxLayout(self.left_grid)
        self.main_figure.setObjectName("main_figure")
        self.horizontalLayout_2.addWidget(self.left_grid)
        self.right_grid = QtWidgets.QWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_grid.sizePolicy().hasHeightForWidth())
        self.right_grid.setSizePolicy(sizePolicy)
        self.right_grid.setMaximumSize(QtCore.QSize(180, 16777215))
        self.right_grid.setObjectName("right_grid")
        self.gridLayout = QtWidgets.QGridLayout(self.right_grid)
        self.gridLayout.setObjectName("gridLayout")
        self.button_fit = QtWidgets.QPushButton(self.right_grid)
        self.button_fit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.button_fit.setObjectName("button_fit")
        self.gridLayout.addWidget(self.button_fit, 0, 0, 1, 1)
        self.edit_samples_line = QtWidgets.QPlainTextEdit(self.right_grid)
        self.edit_samples_line.setMaximumSize(QtCore.QSize(180, 16777215))
        self.edit_samples_line.setObjectName("edit_samples_line")
        self.gridLayout.addWidget(self.edit_samples_line, 18, 0, 1, 2)
        self.edit_highrej_line = QtWidgets.QLineEdit(self.right_grid)
        self.edit_highrej_line.setMaximumSize(QtCore.QSize(70, 16777215))
        self.edit_highrej_line.setObjectName("edit_highrej_line")
        self.gridLayout.addWidget(self.edit_highrej_line, 14, 1, 1, 1)
        self.edit_lowrej_cont = QtWidgets.QLineEdit(self.right_grid)
        self.edit_lowrej_cont.setMaximumSize(QtCore.QSize(70, 16777215))
        self.edit_lowrej_cont.setObjectName("edit_lowrej_cont")
        self.gridLayout.addWidget(self.edit_lowrej_cont, 7, 0, 1, 1)
        self.label_niter_line = QtWidgets.QLabel(self.right_grid)
        self.label_niter_line.setObjectName("label_niter_line")
        self.gridLayout.addWidget(self.label_niter_line, 15, 0, 1, 1)
        self.label_continuum = QtWidgets.QLabel(self.right_grid)
        self.label_continuum.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_continuum.setFont(font)
        self.label_continuum.setObjectName("label_continuum")
        self.gridLayout.addWidget(self.label_continuum, 4, 0, 1, 2)
        self.label_samples_line = QtWidgets.QLabel(self.right_grid)
        self.label_samples_line.setMaximumSize(QtCore.QSize(160, 16777215))
        self.label_samples_line.setObjectName("label_samples_line")
        self.gridLayout.addWidget(self.label_samples_line, 17, 0, 1, 1)
        self.label_samples_cont = QtWidgets.QLabel(self.right_grid)
        self.label_samples_cont.setMaximumSize(QtCore.QSize(160, 16777215))
        self.label_samples_cont.setObjectName("label_samples_cont")
        self.gridLayout.addWidget(self.label_samples_cont, 10, 0, 1, 1)
        self.label_lowrej_line = QtWidgets.QLabel(self.right_grid)
        self.label_lowrej_line.setObjectName("label_lowrej_line")
        self.gridLayout.addWidget(self.label_lowrej_line, 13, 0, 1, 1)
        self.label_niter_cont = QtWidgets.QLabel(self.right_grid)
        self.label_niter_cont.setObjectName("label_niter_cont")
        self.gridLayout.addWidget(self.label_niter_cont, 8, 0, 1, 1)
        self.label_line = QtWidgets.QLabel(self.right_grid)
        self.label_line.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_line.setFont(font)
        self.label_line.setObjectName("label_line")
        self.gridLayout.addWidget(self.label_line, 12, 0, 1, 2)
        self.label_highrej_cont = QtWidgets.QLabel(self.right_grid)
        self.label_highrej_cont.setObjectName("label_highrej_cont")
        self.gridLayout.addWidget(self.label_highrej_cont, 5, 1, 1, 1)
        self.label_highrej_line = QtWidgets.QLabel(self.right_grid)
        self.label_highrej_line.setObjectName("label_highrej_line")
        self.gridLayout.addWidget(self.label_highrej_line, 13, 1, 1, 1)
        self.label_lowrej_cont = QtWidgets.QLabel(self.right_grid)
        self.label_lowrej_cont.setObjectName("label_lowrej_cont")
        self.gridLayout.addWidget(self.label_lowrej_cont, 5, 0, 1, 1)
        self.button_draw = QtWidgets.QPushButton(self.right_grid)
        self.button_draw.setMaximumSize(QtCore.QSize(80, 16777215))
        self.button_draw.setObjectName("button_draw")
        self.gridLayout.addWidget(self.button_draw, 0, 1, 1, 1)
        self.edit_lowrej_line = QtWidgets.QLineEdit(self.right_grid)
        self.edit_lowrej_line.setMaximumSize(QtCore.QSize(70, 16777215))
        self.edit_lowrej_line.setObjectName("edit_lowrej_line")
        self.gridLayout.addWidget(self.edit_lowrej_line, 14, 0, 1, 1)
        self.edit_niter_cont = QtWidgets.QLineEdit(self.right_grid)
        self.edit_niter_cont.setMaximumSize(QtCore.QSize(70, 16777215))
        self.edit_niter_cont.setObjectName("edit_niter_cont")
        self.gridLayout.addWidget(self.edit_niter_cont, 9, 0, 1, 1)
        self.edit_niter_line = QtWidgets.QLineEdit(self.right_grid)
        self.edit_niter_line.setMaximumSize(QtCore.QSize(70, 16777215))
        self.edit_niter_line.setObjectName("edit_niter_line")
        self.gridLayout.addWidget(self.edit_niter_line, 16, 0, 1, 1)
        self.edit_samples_cont = QtWidgets.QPlainTextEdit(self.right_grid)
        self.edit_samples_cont.setMaximumSize(QtCore.QSize(180, 16777215))
        self.edit_samples_cont.setObjectName("edit_samples_cont")
        self.gridLayout.addWidget(self.edit_samples_cont, 11, 0, 1, 2)
        self.edit_highrej_cont = QtWidgets.QLineEdit(self.right_grid)
        self.edit_highrej_cont.setMaximumSize(QtCore.QSize(70, 16777215))
        self.edit_highrej_cont.setObjectName("edit_highrej_cont")
        self.gridLayout.addWidget(self.edit_highrej_cont, 7, 1, 1, 1)
        self.edit_naverage = QtWidgets.QLineEdit(self.right_grid)
        self.edit_naverage.setMaximumSize(QtCore.QSize(70, 16777215))
        self.edit_naverage.setObjectName("edit_naverage")
        self.gridLayout.addWidget(self.edit_naverage, 1, 1, 1, 1)
        self.label_naverage = QtWidgets.QLabel(self.right_grid)
        self.label_naverage.setObjectName("label_naverage")
        self.gridLayout.addWidget(self.label_naverage, 1, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.right_grid)
        self.verticalLayout_3.addWidget(self.frame)
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.frame_6 = QtWidgets.QFrame(Dialog)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_a0 = QtWidgets.QLabel(self.frame_6)
        self.label_a0.setObjectName("label_a0")
        self.horizontalLayout_3.addWidget(self.label_a0)
        self.fix_a0 = QtWidgets.QCheckBox(self.frame_6)
        self.fix_a0.setText("")
        self.fix_a0.setObjectName("fix_a0")
        self.horizontalLayout_3.addWidget(self.fix_a0)
        self.edit_a0 = QtWidgets.QLineEdit(self.frame_6)
        self.edit_a0.setObjectName("edit_a0")
        self.horizontalLayout_3.addWidget(self.edit_a0)
        self.label_a1 = QtWidgets.QLabel(self.frame_6)
        self.label_a1.setObjectName("label_a1")
        self.horizontalLayout_3.addWidget(self.label_a1)
        self.fix_a1 = QtWidgets.QCheckBox(self.frame_6)
        self.fix_a1.setText("")
        self.fix_a1.setObjectName("fix_a1")
        self.horizontalLayout_3.addWidget(self.fix_a1)
        self.edit_a1 = QtWidgets.QLineEdit(self.frame_6)
        self.edit_a1.setObjectName("edit_a1")
        self.horizontalLayout_3.addWidget(self.edit_a1)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.label_5 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_input_wavelength = QtWidgets.QLabel(self.frame_2)
        self.label_input_wavelength.setLineWidth(0)
        self.label_input_wavelength.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_wavelength.setObjectName("label_input_wavelength")
        self.gridLayout_3.addWidget(self.label_input_wavelength, 1, 0, 1, 1)
        self.inwvl1 = QtWidgets.QLineEdit(self.frame_2)
        self.inwvl1.setObjectName("inwvl1")
        self.gridLayout_3.addWidget(self.inwvl1, 3, 0, 1, 2)
        self.inwvl2 = QtWidgets.QLineEdit(self.frame_2)
        self.inwvl2.setObjectName("inwvl2")
        self.gridLayout_3.addWidget(self.inwvl2, 4, 0, 1, 2)
        self.inwvl3 = QtWidgets.QLineEdit(self.frame_2)
        self.inwvl3.setObjectName("inwvl3")
        self.gridLayout_3.addWidget(self.inwvl3, 5, 0, 1, 2)
        self.inwvl4 = QtWidgets.QLineEdit(self.frame_2)
        self.inwvl4.setObjectName("inwvl4")
        self.gridLayout_3.addWidget(self.inwvl4, 6, 0, 1, 2)
        self.inwvl5 = QtWidgets.QLineEdit(self.frame_2)
        self.inwvl5.setObjectName("inwvl5")
        self.gridLayout_3.addWidget(self.inwvl5, 7, 0, 1, 2)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(Dialog)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.fix_dwvl2 = QtWidgets.QCheckBox(self.frame_3)
        self.fix_dwvl2.setText("")
        self.fix_dwvl2.setObjectName("fix_dwvl2")
        self.gridLayout_4.addWidget(self.fix_dwvl2, 4, 0, 1, 1)
        self.fix_dwvl4 = QtWidgets.QCheckBox(self.frame_3)
        self.fix_dwvl4.setText("")
        self.fix_dwvl4.setObjectName("fix_dwvl4")
        self.gridLayout_4.addWidget(self.fix_dwvl4, 6, 0, 1, 1)
        self.fix_dwvl3 = QtWidgets.QCheckBox(self.frame_3)
        self.fix_dwvl3.setText("")
        self.fix_dwvl3.setObjectName("fix_dwvl3")
        self.gridLayout_4.addWidget(self.fix_dwvl3, 5, 0, 1, 1)
        self.edit_dwvl1 = QtWidgets.QLineEdit(self.frame_3)
        self.edit_dwvl1.setObjectName("edit_dwvl1")
        self.gridLayout_4.addWidget(self.edit_dwvl1, 3, 1, 1, 1)
        self.fix_dwvl1 = QtWidgets.QCheckBox(self.frame_3)
        self.fix_dwvl1.setText("")
        self.fix_dwvl1.setObjectName("fix_dwvl1")
        self.gridLayout_4.addWidget(self.fix_dwvl1, 3, 0, 1, 1)
        self.fix_dwvl5 = QtWidgets.QCheckBox(self.frame_3)
        self.fix_dwvl5.setText("")
        self.fix_dwvl5.setObjectName("fix_dwvl5")
        self.gridLayout_4.addWidget(self.fix_dwvl5, 7, 0, 1, 1)
        self.edit_dwvl2 = QtWidgets.QLineEdit(self.frame_3)
        self.edit_dwvl2.setObjectName("edit_dwvl2")
        self.gridLayout_4.addWidget(self.edit_dwvl2, 4, 1, 1, 1)
        self.edit_dwvl3 = QtWidgets.QLineEdit(self.frame_3)
        self.edit_dwvl3.setObjectName("edit_dwvl3")
        self.gridLayout_4.addWidget(self.edit_dwvl3, 5, 1, 1, 1)
        self.edit_dwvl4 = QtWidgets.QLineEdit(self.frame_3)
        self.edit_dwvl4.setObjectName("edit_dwvl4")
        self.gridLayout_4.addWidget(self.edit_dwvl4, 6, 1, 1, 1)
        self.edit_dwvl5 = QtWidgets.QLineEdit(self.frame_3)
        self.edit_dwvl5.setObjectName("edit_dwvl5")
        self.gridLayout_4.addWidget(self.edit_dwvl5, 7, 1, 1, 1)
        self.label_dwvl = QtWidgets.QLabel(self.frame_3)
        self.label_dwvl.setLineWidth(0)
        self.label_dwvl.setAlignment(QtCore.Qt.AlignCenter)
        self.label_dwvl.setObjectName("label_dwvl")
        self.gridLayout_4.addWidget(self.label_dwvl, 2, 1, 1, 1)
        self.share_dwvl = QtWidgets.QCheckBox(self.frame_3)
        self.share_dwvl.setText("")
        self.share_dwvl.setObjectName("share_dwvl")
        self.gridLayout_4.addWidget(self.share_dwvl, 2, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(Dialog)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.fix_fwhm4 = QtWidgets.QCheckBox(self.frame_4)
        self.fix_fwhm4.setText("")
        self.fix_fwhm4.setObjectName("fix_fwhm4")
        self.gridLayout_5.addWidget(self.fix_fwhm4, 5, 0, 1, 1)
        self.fix_fwhm2 = QtWidgets.QCheckBox(self.frame_4)
        self.fix_fwhm2.setText("")
        self.fix_fwhm2.setObjectName("fix_fwhm2")
        self.gridLayout_5.addWidget(self.fix_fwhm2, 3, 0, 1, 1)
        self.fix_fwhm3 = QtWidgets.QCheckBox(self.frame_4)
        self.fix_fwhm3.setText("")
        self.fix_fwhm3.setObjectName("fix_fwhm3")
        self.gridLayout_5.addWidget(self.fix_fwhm3, 4, 0, 1, 1)
        self.fix_fwhm1 = QtWidgets.QCheckBox(self.frame_4)
        self.fix_fwhm1.setText("")
        self.fix_fwhm1.setObjectName("fix_fwhm1")
        self.gridLayout_5.addWidget(self.fix_fwhm1, 2, 0, 1, 1)
        self.edit_fwhm1 = QtWidgets.QLineEdit(self.frame_4)
        self.edit_fwhm1.setObjectName("edit_fwhm1")
        self.gridLayout_5.addWidget(self.edit_fwhm1, 2, 1, 1, 1)
        self.fix_fwhm5 = QtWidgets.QCheckBox(self.frame_4)
        self.fix_fwhm5.setText("")
        self.fix_fwhm5.setObjectName("fix_fwhm5")
        self.gridLayout_5.addWidget(self.fix_fwhm5, 6, 0, 1, 1)
        self.edit_fwhm2 = QtWidgets.QLineEdit(self.frame_4)
        self.edit_fwhm2.setObjectName("edit_fwhm2")
        self.gridLayout_5.addWidget(self.edit_fwhm2, 3, 1, 1, 1)
        self.edit_fwhm3 = QtWidgets.QLineEdit(self.frame_4)
        self.edit_fwhm3.setObjectName("edit_fwhm3")
        self.gridLayout_5.addWidget(self.edit_fwhm3, 4, 1, 1, 1)
        self.edit_fwhm4 = QtWidgets.QLineEdit(self.frame_4)
        self.edit_fwhm4.setObjectName("edit_fwhm4")
        self.gridLayout_5.addWidget(self.edit_fwhm4, 5, 1, 1, 1)
        self.edit_fwhm5 = QtWidgets.QLineEdit(self.frame_4)
        self.edit_fwhm5.setObjectName("edit_fwhm5")
        self.gridLayout_5.addWidget(self.edit_fwhm5, 6, 1, 1, 1)
        self.label_fwhm = QtWidgets.QLabel(self.frame_4)
        self.label_fwhm.setLineWidth(0)
        self.label_fwhm.setAlignment(QtCore.Qt.AlignCenter)
        self.label_fwhm.setObjectName("label_fwhm")
        self.gridLayout_5.addWidget(self.label_fwhm, 0, 1, 1, 1)
        self.share_fwhm = QtWidgets.QCheckBox(self.frame_4)
        self.share_fwhm.setText("")
        self.share_fwhm.setObjectName("share_fwhm")
        self.gridLayout_5.addWidget(self.share_fwhm, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(Dialog)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.edit_gfwhm1 = QtWidgets.QLineEdit(self.frame_5)
        self.edit_gfwhm1.setObjectName("edit_gfwhm1")
        self.gridLayout_6.addWidget(self.edit_gfwhm1, 2, 0, 1, 1)
        self.edit_gfwhm2 = QtWidgets.QLineEdit(self.frame_5)
        self.edit_gfwhm2.setObjectName("edit_gfwhm2")
        self.gridLayout_6.addWidget(self.edit_gfwhm2, 3, 0, 1, 1)
        self.edit_gfwhm3 = QtWidgets.QLineEdit(self.frame_5)
        self.edit_gfwhm3.setObjectName("edit_gfwhm3")
        self.gridLayout_6.addWidget(self.edit_gfwhm3, 4, 0, 1, 1)
        self.edit_gfwhm4 = QtWidgets.QLineEdit(self.frame_5)
        self.edit_gfwhm4.setObjectName("edit_gfwhm4")
        self.gridLayout_6.addWidget(self.edit_gfwhm4, 5, 0, 1, 1)
        self.edit_gfwhm5 = QtWidgets.QLineEdit(self.frame_5)
        self.edit_gfwhm5.setObjectName("edit_gfwhm5")
        self.gridLayout_6.addWidget(self.edit_gfwhm5, 6, 0, 1, 1)
        self.label_gfwhm = QtWidgets.QLabel(self.frame_5)
        self.label_gfwhm.setLineWidth(0)
        self.label_gfwhm.setAlignment(QtCore.Qt.AlignCenter)
        self.label_gfwhm.setObjectName("label_gfwhm")
        self.gridLayout_6.addWidget(self.label_gfwhm, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_5)
        self.frame_7 = QtWidgets.QFrame(Dialog)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.fix_lfwhm4 = QtWidgets.QCheckBox(self.frame_7)
        self.fix_lfwhm4.setText("")
        self.fix_lfwhm4.setObjectName("fix_lfwhm4")
        self.gridLayout_8.addWidget(self.fix_lfwhm4, 5, 0, 1, 1)
        self.fix_lfwhm2 = QtWidgets.QCheckBox(self.frame_7)
        self.fix_lfwhm2.setText("")
        self.fix_lfwhm2.setObjectName("fix_lfwhm2")
        self.gridLayout_8.addWidget(self.fix_lfwhm2, 3, 0, 1, 1)
        self.fix_lfwhm3 = QtWidgets.QCheckBox(self.frame_7)
        self.fix_lfwhm3.setText("")
        self.fix_lfwhm3.setObjectName("fix_lfwhm3")
        self.gridLayout_8.addWidget(self.fix_lfwhm3, 4, 0, 1, 1)
        self.fix_lfwhm1 = QtWidgets.QCheckBox(self.frame_7)
        self.fix_lfwhm1.setText("")
        self.fix_lfwhm1.setObjectName("fix_lfwhm1")
        self.gridLayout_8.addWidget(self.fix_lfwhm1, 2, 0, 1, 1)
        self.edit_lfwhm1 = QtWidgets.QLineEdit(self.frame_7)
        self.edit_lfwhm1.setObjectName("edit_lfwhm1")
        self.gridLayout_8.addWidget(self.edit_lfwhm1, 2, 1, 1, 1)
        self.fix_lfwhm5 = QtWidgets.QCheckBox(self.frame_7)
        self.fix_lfwhm5.setText("")
        self.fix_lfwhm5.setObjectName("fix_lfwhm5")
        self.gridLayout_8.addWidget(self.fix_lfwhm5, 6, 0, 1, 1)
        self.edit_lfwhm2 = QtWidgets.QLineEdit(self.frame_7)
        self.edit_lfwhm2.setObjectName("edit_lfwhm2")
        self.gridLayout_8.addWidget(self.edit_lfwhm2, 3, 1, 1, 1)
        self.edit_lfwhm3 = QtWidgets.QLineEdit(self.frame_7)
        self.edit_lfwhm3.setObjectName("edit_lfwhm3")
        self.gridLayout_8.addWidget(self.edit_lfwhm3, 4, 1, 1, 1)
        self.edit_lfwhm4 = QtWidgets.QLineEdit(self.frame_7)
        self.edit_lfwhm4.setObjectName("edit_lfwhm4")
        self.gridLayout_8.addWidget(self.edit_lfwhm4, 5, 1, 1, 1)
        self.edit_lfwhm5 = QtWidgets.QLineEdit(self.frame_7)
        self.edit_lfwhm5.setObjectName("edit_lfwhm5")
        self.gridLayout_8.addWidget(self.edit_lfwhm5, 6, 1, 1, 1)
        self.label_lfwhm = QtWidgets.QLabel(self.frame_7)
        self.label_lfwhm.setLineWidth(0)
        self.label_lfwhm.setAlignment(QtCore.Qt.AlignCenter)
        self.label_lfwhm.setObjectName("label_lfwhm")
        self.gridLayout_8.addWidget(self.label_lfwhm, 0, 1, 1, 1)
        self.horizontalLayout.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(Dialog)
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.edit_EW1 = QtWidgets.QLineEdit(self.frame_8)
        self.edit_EW1.setObjectName("edit_EW1")
        self.gridLayout_9.addWidget(self.edit_EW1, 2, 1, 1, 1)
        self.edit_EW2 = QtWidgets.QLineEdit(self.frame_8)
        self.edit_EW2.setObjectName("edit_EW2")
        self.gridLayout_9.addWidget(self.edit_EW2, 3, 1, 1, 1)
        self.edit_EW3 = QtWidgets.QLineEdit(self.frame_8)
        self.edit_EW3.setObjectName("edit_EW3")
        self.gridLayout_9.addWidget(self.edit_EW3, 4, 1, 1, 1)
        self.edit_EW4 = QtWidgets.QLineEdit(self.frame_8)
        self.edit_EW4.setObjectName("edit_EW4")
        self.gridLayout_9.addWidget(self.edit_EW4, 5, 1, 1, 1)
        self.edit_EW5 = QtWidgets.QLineEdit(self.frame_8)
        self.edit_EW5.setObjectName("edit_EW5")
        self.gridLayout_9.addWidget(self.edit_EW5, 6, 1, 1, 1)
        self.label_EW = QtWidgets.QLabel(self.frame_8)
        self.label_EW.setLineWidth(0)
        self.label_EW.setAlignment(QtCore.Qt.AlignCenter)
        self.label_EW.setObjectName("label_EW")
        self.gridLayout_9.addWidget(self.label_EW, 0, 1, 1, 1)
        self.horizontalLayout.addWidget(self.frame_8)
        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.button_fit.setText(_translate("Dialog", "Fit"))
        self.label_niter_line.setText(_translate("Dialog", "n_iterate"))
        self.label_continuum.setText(_translate("Dialog", "Continuum"))
        self.label_samples_line.setText(_translate("Dialog", "samples"))
        self.label_samples_cont.setText(_translate("Dialog", "samples"))
        self.label_lowrej_line.setText(_translate("Dialog", "low_rej"))
        self.label_niter_cont.setText(_translate("Dialog", "n_iterate"))
        self.label_line.setText(_translate("Dialog", "Lines"))
        self.label_highrej_cont.setText(_translate("Dialog", "high_rej"))
        self.label_highrej_line.setText(_translate("Dialog", "high_rej"))
        self.label_lowrej_cont.setText(_translate("Dialog", "low_rej"))
        self.button_draw.setText(_translate("Dialog", "Redraw"))
        self.label_naverage.setText(_translate("Dialog", "n_average"))
        self.label.setText(_translate("Dialog", "Continuum Output"))
        self.label_a0.setText(_translate("Dialog", "a0"))
        self.label_a1.setText(_translate("Dialog", "a1"))
        self.label_5.setText(_translate("Dialog", "Line Output"))
        self.label_input_wavelength.setText(_translate("Dialog", "input wavelength"))
        self.label_dwvl.setText(_translate("Dialog", "delta_wavelength"))
        self.label_fwhm.setText(_translate("Dialog", "FWHM"))
        self.label_gfwhm.setText(_translate("Dialog", "gFWHM"))
        self.label_lfwhm.setText(_translate("Dialog", "lFWHM"))
        self.label_EW.setText(_translate("Dialog", "EW"))

