# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqtcontinuum.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(780, 520)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_grid = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_grid.sizePolicy().hasHeightForWidth())
        self.left_grid.setSizePolicy(sizePolicy)
        self.left_grid.setObjectName("left_grid")
        self.main_figure = QtWidgets.QVBoxLayout(self.left_grid)
        self.main_figure.setObjectName("main_figure")
        self.horizontalLayout.addWidget(self.left_grid)
        self.right_grid = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_grid.sizePolicy().hasHeightForWidth())
        self.right_grid.setSizePolicy(sizePolicy)
        self.right_grid.setMaximumSize(QtCore.QSize(180, 16777215))
        self.right_grid.setObjectName("right_grid")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.right_grid)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.button_fit = QtWidgets.QPushButton(self.right_grid)
        self.button_fit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.button_fit.setObjectName("button_fit")
        self.gridLayout_2.addWidget(self.button_fit, 0, 0, 1, 1)
        self.button_draw = QtWidgets.QPushButton(self.right_grid)
        self.button_draw.setMaximumSize(QtCore.QSize(80, 16777215))
        self.button_draw.setObjectName("button_draw")
        self.gridLayout_2.addWidget(self.button_draw, 0, 1, 1, 1)
        self.label_function = QtWidgets.QLabel(self.right_grid)
        self.label_function.setMaximumSize(QtCore.QSize(160, 16777215))
        self.label_function.setObjectName("label_function")
        self.gridLayout_2.addWidget(self.label_function, 1, 0, 1, 2)
        self.edit_function = QtWidgets.QLineEdit(self.right_grid)
        self.edit_function.setMaximumSize(QtCore.QSize(160, 16777215))
        self.edit_function.setObjectName("edit_function")
        self.gridLayout_2.addWidget(self.edit_function, 2, 0, 1, 2)
        self.label_knots = QtWidgets.QLabel(self.right_grid)
        self.label_knots.setMaximumSize(QtCore.QSize(160, 16777215))
        self.label_knots.setObjectName("label_knots")
        self.gridLayout_2.addWidget(self.label_knots, 3, 0, 1, 2)
        self.edit_knots = QtWidgets.QLineEdit(self.right_grid)
        self.edit_knots.setMaximumSize(QtCore.QSize(70, 16777215))
        self.edit_knots.setObjectName("edit_knots")
        self.gridLayout_2.addWidget(self.edit_knots, 4, 0, 1, 1)
        self.label_lowrej = QtWidgets.QLabel(self.right_grid)
        self.label_lowrej.setObjectName("label_lowrej")
        self.gridLayout_2.addWidget(self.label_lowrej, 5, 0, 1, 1)
        self.label_highrej = QtWidgets.QLabel(self.right_grid)
        self.label_highrej.setObjectName("label_highrej")
        self.gridLayout_2.addWidget(self.label_highrej, 5, 1, 1, 1)
        self.edit_lowrej = QtWidgets.QLineEdit(self.right_grid)
        self.edit_lowrej.setMaximumSize(QtCore.QSize(70, 16777215))
        self.edit_lowrej.setObjectName("edit_lowrej")
        self.gridLayout_2.addWidget(self.edit_lowrej, 6, 0, 1, 1)
        self.edit_highrej = QtWidgets.QLineEdit(self.right_grid)
        self.edit_highrej.setMaximumSize(QtCore.QSize(70, 16777215))
        self.edit_highrej.setObjectName("edit_highrej")
        self.gridLayout_2.addWidget(self.edit_highrej, 6, 1, 1, 1)
        self.label_niter = QtWidgets.QLabel(self.right_grid)
        self.label_niter.setObjectName("label_niter")
        self.gridLayout_2.addWidget(self.label_niter, 7, 0, 1, 1)
        self.label_nave = QtWidgets.QLabel(self.right_grid)
        self.label_nave.setObjectName("label_nave")
        self.gridLayout_2.addWidget(self.label_nave, 7, 1, 1, 1)
        self.edit_niter = QtWidgets.QLineEdit(self.right_grid)
        self.edit_niter.setMaximumSize(QtCore.QSize(70, 16777215))
        self.edit_niter.setObjectName("edit_niter")
        self.gridLayout_2.addWidget(self.edit_niter, 8, 0, 1, 1)
        self.edit_nave = QtWidgets.QLineEdit(self.right_grid)
        self.edit_nave.setMaximumSize(QtCore.QSize(70, 16777215))
        self.edit_nave.setObjectName("edit_nave")
        self.gridLayout_2.addWidget(self.edit_nave, 8, 1, 1, 1)
        self.label_grow = QtWidgets.QLabel(self.right_grid)
        self.label_grow.setObjectName("label_grow")
        self.gridLayout_2.addWidget(self.label_grow, 9, 0, 1, 1)
        self.edit_grow = QtWidgets.QLineEdit(self.right_grid)
        self.edit_grow.setMaximumSize(QtCore.QSize(80, 16777215))
        self.edit_grow.setMouseTracking(True)
        self.edit_grow.setObjectName("edit_grow")
        self.gridLayout_2.addWidget(self.edit_grow, 10, 0, 1, 1)
        self.label_samples = QtWidgets.QLabel(self.right_grid)
        self.label_samples.setMaximumSize(QtCore.QSize(160, 16777215))
        self.label_samples.setObjectName("label_samples")
        self.gridLayout_2.addWidget(self.label_samples, 11, 0, 1, 2)
        self.edit_samples = QtWidgets.QPlainTextEdit(self.right_grid)
        self.edit_samples.setMaximumSize(QtCore.QSize(180, 16777215))
        self.edit_samples.setObjectName("edit_samples")
        self.gridLayout_2.addWidget(self.edit_samples, 12, 0, 1, 2)
        self.horizontalLayout.addWidget(self.right_grid, 0, QtCore.Qt.AlignRight)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.button_fit.setText(_translate("Dialog", "Fit"))
        self.button_draw.setText(_translate("Dialog", "Redraw"))
        self.label_function.setText(_translate("Dialog", "function"))
        self.label_knots.setText(_translate("Dialog", "dwvl_knots"))
        self.label_lowrej.setText(_translate("Dialog", "low_rej"))
        self.label_highrej.setText(_translate("Dialog", "high_rej"))
        self.label_niter.setText(_translate("Dialog", "n_iterate"))
        self.label_nave.setText(_translate("Dialog", "n_average"))
        self.label_grow.setText(_translate("Dialog", "grow"))
        self.label_samples.setText(_translate("Dialog", "samples"))

